// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: more_mesage.proto

package proto;

public interface CsvRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CsvRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 generated_at = 1;</code>
   * @return The generatedAt.
   */
  long getGeneratedAt();

  /**
   * <code>repeated double values = 2;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Double> getValuesList();
  /**
   * <code>repeated double values = 2;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated double values = 2;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  double getValues(int index);
}
