// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: more_mesage.proto

package proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 message_sent_at = 1;</code>
   * @return The messageSentAt.
   */
  long getMessageSentAt();

  /**
   * <code>repeated .proto.CsvRow csv_rows = 2;</code>
   */
  java.util.List<proto.CsvRow> 
      getCsvRowsList();
  /**
   * <code>repeated .proto.CsvRow csv_rows = 2;</code>
   */
  proto.CsvRow getCsvRows(int index);
  /**
   * <code>repeated .proto.CsvRow csv_rows = 2;</code>
   */
  int getCsvRowsCount();
  /**
   * <code>repeated .proto.CsvRow csv_rows = 2;</code>
   */
  java.util.List<? extends proto.CsvRowOrBuilder> 
      getCsvRowsOrBuilderList();
  /**
   * <code>repeated .proto.CsvRow csv_rows = 2;</code>
   */
  proto.CsvRowOrBuilder getCsvRowsOrBuilder(
      int index);
}
